### ISSUE TITLE
Add Attributes

### ISSUE THREAD

**Issue by Srijan-crypto** [opencodeiiita/SolMintNFT#16]
Add attributes( i.e.  **_program_id** and **accounts** , of the same name as just specified ) to `process_instruction` in [../src/lib.rs](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/program/src/lib.rs) using parameters of the `use` statements at the beginning of [../src/lib.rs ](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/program/src/lib.rs)

**Comment by Finesse-734** [comment]
claim

**Comment by Srijan-crypto** [comment]
Assigned to you @Finesse-734

**Comment by Finesse-734** [comment]
@Srijan-crypto using which parameters do we have to add the required attributes to the process_instruction??

**Comment by Tan-Code-may** [comment]
@Finesse-734 Deadline for you to complete this issue is today at 2 P.M.

**Comment by Finesse-734** [comment]
@Tan-Code-may apologies but currently I am out of town and will not be able to complete the issue within the required time frame. Could it be extended till midnight today if possible??

**Comment by Srijan-crypto** [comment]
@Finesse-734 we are extending the deadline till midnight sharp. And the parameters used would be `Pubkey` and `AccountInfo`. No more extensions will be provided. All the best and happy contributing !
