### ISSUE TITLE
Import and set up a new connection

### ISSUE THREAD

**Issue by Srijan-crypto** [opencodeiiita/SolMintNFT#26]
Import `createKeypairFromFile` from [NFT_RUST/util.ts](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/util.ts) and set up a **new connection** just inside `main` with the **Fullnode JSON RPC** endpoint at [https://api.devnet.solana.com/](https://api.devnet.solana.com/) and **Commitment** as _confirmed_.  All this to be done in [NFT_RUST/app.ts](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/app.ts)

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by Ayashika** [comment]
Claim

**Comment by Srijan-crypto** [comment]
Assigned to you @SanyamAgrawal07
