### ISSUE TITLE
Complete the invoke instruction

### ISSUE THREAD

**Issue by Srijan-crypto** [opencodeiiita/SolMintNFT#28]
Complete the `invoke` instruction for `mint_to` and `create_account`  in [../src/lib.rs](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/program/src/lib.rs) .

Include all these for `mint_to` :  
token_program_id ,
                                                   mint_pubkey ,
                                                   account_pubkey ,
                                                   owner_pubkey ,
                                                   signer_pubkeys ,
                                                   amount 

And, Include all these for `create_account` :
from_pubkey ,
to_pubkey ,
lamports ,
space ,
owner

Take the help of other completed invoke instructions !

**Comment by akshatsgh** [comment]
Claim

**Comment by anshgeez31** [comment]
Claim

**Comment by Tan-Code-may** [comment]
Go ahead @anshgeez31

**Comment by Srijan-crypto** [comment]
@anshgeez31 you have 4 hours left to complete this issue.

**Comment by anshgeez31** [comment]
@Srijan-crypto I need more time for corrections

**Comment by Srijan-crypto** [comment]
OK @anshgeez31 you have till 12 midnight tomorrow. Try to complete it in time.
