### ISSUE TITLE
Remove the Bug

### ISSUE THREAD

**Issue by Srijan-crypto** [opencodeiiita/SolMintNFT#31]
Rectify the bug present in [../src/lib.rs](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/program/src/lib.rs) .

**Comment by SanyamAgrawal07** [comment]
Claim

**Comment by akshatsgh** [comment]
claim

**Comment by Ayashika** [comment]
Claim

**Comment by Tan-Code-may** [comment]
Go ahead @akshatsgh

**Comment by sushantk1274** [comment]
claim

**Comment by Srijan-crypto** [comment]
@akshatsgh 1.5 hours left for you to complete this issue.

**Comment by Srijan-crypto** [comment]
Issue is up for claims again!

**Comment by sushantk1274** [comment]
claim
