### ISSUE TITLE
Random Keypair

### ISSUE THREAD

**Issue by Srijan-crypto** [opencodeiiita/SolMintNFT#38]
Create a const variable `mintKeypair` of the type **Keypair** , (we imported it in [util.ts](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/util.ts) :-  import {Keypair} from ‘@solana/web3.js’ ) , in [NFT_RUST/app.ts](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/app.ts) , that would store a newly generated valid keypair which is also unique.

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by Srijan-crypto** [comment]
Go ahead @SanyamAgrawal07

**Comment by abhinavs1920** [comment]
Claim

**Comment by Srijan-crypto** [comment]
I have updated the repo , pull the changes first !

**Comment by Sushi1274** [comment]
claim

**Comment by sushantk1274** [comment]
claim
