### ISSUE TITLE
Initiate Program Execution

### ISSUE THREAD

**Issue by Srijan-crypto** [opencodeiiita/SolMintNFT#4]
Write command { macro(i.e. !) has to be a part of that command } to begin program execution in [../src/lib.rs](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/program/src/lib.rs) , which calls the necessary function to process the program instructions , as we do not have a **main** function here .

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by hargunkaur286** [comment]
claim

**Comment by Srijan-crypto** [comment]
@SanyamAgrawal07  Reminder - 3 hours left for you to complete this issue.
