### ISSUE TITLE
Missing properties!

### ISSUE THREAD

**Issue by Srijan-crypto** [opencodeiiita/SolMintNFT#42]
Type  **{ }**  is missing the following properties from type **AccountMeta** : `pubkey` , `isSigner` , `isWritable` , for `Mint account` ,
`Rent account` , `Token program` and `Associated token program` components in **TransactionInstruction.keys** .  Complete them in [NFT_RUST/app.ts](https://github.com/opencodeiiita/SolMintNFT/blob/main/NFT-RUST/app.ts)  .

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by Srijan-crypto** [comment]
go ahead @SanyamAgrawal07

**Comment by sushantk1274** [comment]
claim
