### ISSUE TITLE
Building generative NFTs 

### ISSUE THREAD

**Issue by Tan-Code-may** [opencodeiiita/SolMintNFT#47]
We will be building generative NFTs using a tool known as the Hashlips Art Engine. Switch to the hashlips_art_engine directory and do the following tasks before generating NFTs.

# Procedure- 
1. Locate the layers folder and inside it change the rarity weight of various assets/ layers as mentioned using the rarity delimiter '#'-
- **Bottom lid:** High- 30%, Low- 40%, Middle- 30%.
- **Eye color:** Cyan- 10%, Green- 10%, Pink- 10%, Purple- 20%, Red- 20%, Yellow- 30%.
- **Eyeball:** Red- 70%, White- 30%.
- **Iris:** Large- 25%, Medium- 50%, Small- 25%.
- **Top lid:** High- 20%, Low- 40%, Middle- 40%.
2. Now, switch to the config.js file inside the src folder of the cd. All the further changes need to be done only inside this file.
3. Set the network to Solana.
4. Mark the symbol as AOE and set the royalty percentage to 6%.
5. Add the creators and their respective shares in the metadata. Use the following wallet addresses to add them with each of them having equal shares-
- > hd8pVhXSRx3K5TEKus9PP3CkQ95E9UUcDmc6H9S7eFH
- > Dq9SmVjaRpH5Bec5n8KoZALcVgbqQAJ6SnGw6SUMuQCZ
6. Two kinds of layer orders need to be set up inside the layerConfigurations, with the first kind of layer producing 15 artworks and the second layer another 10 artworks-
- Background, Eyeball, Eye color, Iris, Shine, Bottom lid, Top lid.
- Background, Eyeball, Eye color, Iris, Top lid, Bottom lid, Shine.
7. Specify the height: 600 px. and width: 600 px. of the NFTs.
8. Fill the ratio of the pixels as 3/128.

Finally, after following the above procedure generate the NFTs, and our outputted art will be in the build/images directory and the json in the build/json directory.

---
Feel free to ping me on our discord channel if you have any doubts.

**Comment by sushantk1274** [comment]
Claim

**Comment by Tan-Code-may** [comment]
@sushantk1274 You already have 3 issues assigned.

**Comment by akshatsgh** [comment]
Claim

**Comment by Tan-Code-may** [comment]
@akshatsgh Go Ahead! Best of luck! You only have 24 hrs. to complete this task.

**Comment by Tan-Code-may** [comment]
@akshatsgh Complete this issue by today midnight.

**Comment by akshatsgh** [comment]
@Tan-Code-may I need some more time

**Comment by Tan-Code-may** [comment]
@akshatsgh Fine till noon.
