### ISSUE TITLE
Set up the Solana CLI and your account

### ISSUE THREAD

**Issue by Tan-Code-may** [opencodeiiita/SolMintNFT#5]
OPEN TO ALL.
NO need to claim this issue.

* Set up the **Solana CLI** and generate a new **Solana keypair** and display the configurations in a screenshot, as shown in the image below. Also, airdrop some sol in your account and display the public key and the balance. 
* Insert a new text file in the Task-5 folder with your name, and provide your wallet address in that text file.

PS:  Attach the screenshot while submitting the PR, and make sure that the ss looks exactly like the one attached below, that is commands used should be hidden.
Note: A text file named **tanmay.txt** is present in that folder for your reference.

---

![](https://user-images.githubusercontent.com/95227013/208238373-1ad83a01-473b-48f8-ba83-f6e9100b3636.jpeg)

---

Feel free to ping us in our discord channel in case of any doubts.

**Comment by anshgeez31** [comment]
Claim

**Comment by Tan-Code-may** [comment]
@anshgeez31 No need to claim this issue, you can directly submit a PR as mentioned above. Happy Contributing!
