### ISSUE TITLE
Minting assests using Sugar candy machine CLI

### ISSUE THREAD

**Issue by Tan-Code-may** [opencodeiiita/SolMintNFT#50]
You need to mint the NFTs generated in the previous task of the 'hashlips art engine' using the Sugar Candy Machine CLI. In order to do so follow the below-mentioned steps-
1. Transfer all the images and the json files in the build folder of the hashlips_art_engine to the assets folder of the metaplex.
2. Delete previously present text file in the assets folder.
3. Then, mint all those NFTs to Bundlr using the Sugar Candy Machine CLI.
4. Price of each NFT will be 0.15 sol.
5. Royalty percentage: 6%.
6. Go live date: 17/01/2023 and time: 00:00:00 hrs.
---

Feel free to contact on discord.

**Comment by akshatsgh** [comment]
Claim

**Comment by Tan-Code-may** [comment]
Go ahead, and try to complete it asap.
