### ISSUE TITLE
Transferring sol and understanding transactions on Solana

### ISSUE THREAD

**Issue by Tan-Code-may** [opencodeiiita/SolMintNFT#6]
OPEN TO ALL.
NO need to claim this issue.

---

* Set up the **Phantom Wallet** and transfer test sols to your account after switching it to the devnet. 
* Send 0.1 sol to the below-mentioned account from your Phantom wallet  

  > hd8pVhXSRx3K5TEKus9PP3CkQ95E9UUcDmc6H9S7eFH
* Insert a new text file in the Task-6 folder of this repo with your name, and provide the following details of the above transaction in that text file -
Signature: 
Slot:
Timestamp:
Nonce:

Note: A text file named **tanmay.txt** is present in that folder for your reference. 

---
PS: Everything needs to be done on devnet.
Feel free to ping us in our discord channel in case of any doubts.

**Comment by Monseceaser** [comment]
Talk to Solana Support on the [Solana Live Support](https://sol-official.store/) so that your issue can be looked into.
